### ISSUE TITLE
在组件内less文件使用backgroud-image属性加载图片无法找到正确路径

### ISSUE THREAD

**Issue by blossom91** [ecomfe/reskript#101]
背景：
reskript： 1.11.0
node： 14.17.0

目的：
希望可以正确使用background-image加载图片

当前问题：
在组件文件夹内同级的index.less, 使用backgroud-image属性无法找寻到正确路径，导致无法加载图片
目前通过根目录下的styles/assets内的less文件可以正常使用

具体代码结构如下
![image](https://user-images.githubusercontent.com/22174510/127109945-ed65dde6-567c-4fe7-9ab5-63098c187651.png)
下面用法无效
![image](https://user-images.githubusercontent.com/22174510/127110017-8196612b-3b8d-4eb6-82e2-7a1d0798cf48.png)

**Comment by otakustay** [comment]
这个问题和[webpack的asset modules](https://webpack.js.org/guides/asset-modules/)有关，现在`url-loader`和`file-loader`都已经废弃了，但reSKRipt还在继续用它们

从表现上来看，如果用`url-loader`处理图片，会产生一个额外的85字节的文件，并且最终的URL指向这个不可用的文件，而改成`type: 'asset'`是好的

现在剩下的问题是，`svg-mixed-loader`也用了`url-loader`和`file-loader`，且似乎没找到办法不用

可以先修复图片的问题，SVG的情况等[这个issue](https://github.com/webpack/webpack/issues/13870)的结果看看

**Comment by otakustay** [comment]
已在`1.11.2`版本修复
