### ISSUE TITLE
@reskript/init 初始化项目之后安装依赖报错

### ISSUE THREAD

**Issue by heart-er** [ecomfe/reskript#116]
现场图片
![image](https://user-images.githubusercontent.com/24717511/129649662-73187cf5-189f-4d76-a37c-8b85ba22e916.png)

**Comment by heart-er** [comment]
还有第二个问题，init的时候项目代码已经被生成了，但是init失败的时候，package.json中的依赖不全，只有 react 和 react-dom
![image](https://user-images.githubusercontent.com/24717511/129649806-f5d84ef3-ba46-4f3d-a0eb-83b3da7699f7.png)

这就导致我自己npm install的时候 提示skr命令不存在
![image](https://user-images.githubusercontent.com/24717511/129649839-0a3fbb86-c0db-454f-83a6-968fb021aca0.png)

**Comment by otakustay** [comment]
因为依赖是用`npm install`往里加的，这个问题是install的环节出错了，所以依赖就没写进去
