### ISSUE TITLE
期望能够引入 tailwindCSS配置

### ISSUE THREAD

**Issue by heart-er** [ecomfe/reskript#119]
Create-React-App 配置：
https://github.com/heart-er/use-tailwind-config

官方对于 Create-react-app的配置链接：
https://docs.tailwindchina.com/docs/guides/create-react-app
@otakustay

**Comment by otakustay** [comment]
大致了解了，但考虑到`webpack-dev-server`发了4.0版本，近期skr也会相应升到2.0版本适配它

预期2.0版本的BREAKING会比较少，所以我打算将新功能也推到2.0去

**Comment by otakustay** [comment]
还需要在 https://github.com/ecomfe/stylelint-config/blob/master/index.js 加上对`@tailwind`的支持

**Comment by otakustay** [comment]
已在`2.0.0-beta.*`中实现，近期发正式版
