### ISSUE TITLE
增加 skr play 的全局 setup 配置

### ISSUE THREAD

**Issue by dancerphil** [ecomfe/reskript#120]
在 skr play 的时候，有部分组件会有相同的依赖，希望有一个统一的配置入口

**Comment by otakustay** [comment]
我在想，这东西应该是一个命令行参数，`skr play --config=src/components/App/__repl__/index.play.js`，这样有可能可以用不同的配置来测不同环境

但这样的坏处是，命令实在太长了……而且让VSCode的插件来配置也不方便

另外，我建议全局配置直接是`App`组件的配置，这样好说明情况（大概率这东西和`entries/index.tsx`长得很像）

**Comment by otakustay** [comment]
1. 计划增加一个`defaultGlobalSetup`的字符串属性，默认加载这个
2. 但允许用`--setup`参数覆盖它
3. 全局允许提供`provides`和`Wrapper`，与局部的`provides`合并，`Wrapper`则形成嵌套
4. 此功能之后，`injectResources`属性标记为deprecated，2.0删除
