### ISSUE TITLE
本地开发环境devServer代理时的origin

### ISSUE THREAD

**Issue by chinanoi** [ecomfe/reskript#156]
目前本地环境做代理配置的后，发出的请求的origin是未做代理的发起者的域名。会导致出现403 forbidden的请求被拒绝问题，看看能否处理一下，把origin改成proxy的目标地址，或者不带上origin。

**Comment by chinanoi** [comment]
> 我看了一下配置，现在`reSKRipt`已经有`changeOrigin: true`这个配置，即会把`Origin`头改成目标地址的域名
> 
> 能否再详细说明一下你的情况，或者有网络包的记录（非Chrome调试看到的）

额  文档里没有配置说明

**Comment by otakustay** [comment]
`changeOrigin`是默认配置且不可修改，但这个配置应该不会在你的实际应用中产生问题，所以我希望了解你的具体情况，后端是否确实因为`Origin`头的问题而返回了403，以及从dev server发送给后端的请求里的`Origin`具体是什么值
