### ISSUE TITLE
新增参数可控制 开发环境自动打开游览器 功能

### ISSUE THREAD

**Issue by blossom91** [ecomfe/reskript#160]
希望 exports.devServer  新增 autoOpen 之类的参数，用于控制是否自动打开游览器功能

也希望以后能够支持多页面同端口开发环境支持

**Comment by otakustay** [comment]
关于多入口单个devServer的问题，主要问题是在用什么样的URL来访问不同入口比较好

比如说你有`foo`和`bar`两个入口，然后`foo`里面有个`/bar`的路由……这就很难受了

一种办法是加个前缀，比如`localhost/_/foo`就是入口，`localhost/foo`就不是入口而是一个路由，但这种会要求你的路由有`basename`，又是对代码的侵入性

**Comment by otakustay** [comment]
使用`--no-open`可以控制不打开页面
