### ISSUE TITLE
设置多个代理路由

### ISSUE THREAD

**Issue by isee15** [ecomfe/reskript#172]
exports.devServer = {
    port: 8200, // TODO: 找一个不和其它系统冲突的端口
    apiPrefixes: ['/api/xxxx'], // TODO: 设置后端API的URL前缀
    defaultProxyDomain: 'localhost:8300' // TODO: 设置后端测试环境域名
};
在后端微服务和多个开发团队的场景下，有时候在开发阶段需要配置 /api/xxx 代理到  server.com:8001, /api/yyyy  代理到  server.com:8002

**Comment by otakustay** [comment]
请参考一下这个，看是否满足：https://ecomfe.github.io/reskript/docs/settings/dev-server#%E5%A4%9A%E5%90%8E%E7%AB%AF%E4%BB%A3%E7%90%86%E9%85%8D%E7%BD%AE

**Comment by isee15** [comment]
可以满足

**Comment by zhourm3659** [comment]
> 请参考一下这个，看是否满足：https://ecomfe.github.io/reskript/docs/settings/dev-server#%E5%A4%9A%E5%90%8E%E7%AB%AF%E4%BB%A3%E7%90%86%E9%85%8D%E7%BD%AE

地址失效了，还有新的吗

**Comment by isee15** [comment]
> > 请参考一下这个，看是否满足：https://ecomfe.github.io/reskript/docs/settings/dev-server#%E5%A4%9A%E5%90%8E%E7%AB%AF%E4%BB%A3%E7%90%86%E9%85%8D%E7%BD%AE
> 
> 地址失效了，还有新的吗

https://reskript.dev/docs/settings/dev-server 多后端代理配置
