### ISSUE TITLE
增加 $build.entry 判断 entry，进而进行 code split

### ISSUE THREAD

**Issue by dancerphil** [ecomfe/reskript#173]
期望

```ts
const feature = $build.entry === 'nextVersion' ? featureNext : noop;
```

被编译为

```ts
// $build.entry === 'nextVersion' 时
const feature = featureNext;

// $build.entry === 'index' 时
const feature = noop;
```

**Comment by otakustay** [comment]
我看了一下相关实现，这个需求会比较麻烦。按照`reSKRipt`的逻辑，不同的feature set（`featureMatrix`里写的）会分开构建。而每一次构建会包含所有的`entries/*`

在一轮构建里，是不分入口的，因为多入口共享的模块只能编译成同样的产出，多entry也会共享这些chunk。

如果要分entry来产生不同的结果，那么就必须不同的entry也分开构建，最终N个feature set加上M个入口，会变成N*M次构建，无论如何这个速度是不能接受的。

因此，事实上只有`skr build --entries-only`参数指定且仅指定一个entry时，才能做`$build.entry`这样的功能，这个对用户来说成本太高了。

如果确实仅构建一个entry，且要区分，我还是建议设置`process.env.SKR_BUILD_ENTRY`之类的环境变量来处理比较合适。如果是多entry同时构建，那么这个功能理论上无法实现
