### ISSUE TITLE
skr lint --fix支持自动将修复好的文件加入staged

### ISSUE THREAD

**Issue by suica** [ecomfe/reskript#177]
# 现状
若配置`pre-commit`时执行`skr lint --staged --fix`之后，commit时，`skr lint`会进行lint修复，但不会把修复好的文件加入staged。同时需要注意的是，这个commit中可能包含不通过lint的代码。

# 预期
1. `skr lint`提供将fixed的文件自动加入staged的参数，或者其他类似的能力暴露。这样，就不需要自己手动再将`skr lint`执行的修改加入staged。

**Comment by otakustay** [comment]
增加一个`--auto-stage`的参数，有该参数时，将所有执行了`git add`并且没有进一步修改的文件自动stage
