### ISSUE TITLE
init输出详细过程

### ISSUE THREAD

**Issue by otakustay** [ecomfe/reskript#189]
skr安装依赖的时候 这个过程的详细内容可以显示出来么 因为时间挺久的 想看看到哪一步了

**Comment by otakustay** [comment]
我们全局有一个`SKR_LOGGING=debug`的环境变量，可以复用这个，然后把安装过程pipe到stdout上

**Comment by heart-er** [comment]
逐个显示安装的依赖项比较麻烦，也不是使用者关注的

就是想看一下百分比的进度条（原因是 之前有几次因为网络的原因 一只 retry 然后最后被spawn抛出了错误，所以加一个百分比的进度是不是好一点）

**Comment by otakustay** [comment]
> 就是想看一下百分比的进度条

`yarn`和`npm`本身就不给我进度，做不到啊……现在唯一的进度就是一共4步，现在在第3步（装dev依赖），但这一步能卡你10分钟没商量

**Comment by heart-er** [comment]
> 我们全局有一个`SKR_LOGGING=debug`的环境变量，可以复用这个，然后把安装过程pipe到stdout上

因为是npx init初始化的时候 比较久 然后有时候又因为网络原因 就... 不知道具体到哪里了

**Comment by heart-er** [comment]
> > 就是想看一下百分比的进度条
> 
> `yarn`和`npm`本身就不给我进度，做不到啊……现在唯一的进度就是一共4步，现在在第3步（装dev依赖），但这一步能卡你10分钟没商量

对 之前安装 下载了二十五分钟 - -|||
