### ISSUE TITLE
如何配置兼容ie

### ISSUE THREAD

**Issue by wangqiaoling01** [ecomfe/reskript#196]

**Comment by otakustay** [comment]
单纯的JS兼容性的话，使用`.browserslistrc`就行：https://ecomfe.github.io/reskript/docs/advanced/browsers-list

如果有第三方库不兼容IE，需要babel转换的话：https://ecomfe.github.io/reskript/docs/settings/build#增加babel编译的文件

其它情况的话，可以再讨论

**Comment by wangqiaoling01** [comment]
打包之后有箭头函数，在IE9上打不开项目。
安装了regenerator-runtime

.browserlistrc配置如下：
> 0.5%
last 2 versions
Firefox ESR
not dead
ie 9

**Comment by otakustay** [comment]
确认一下配置文件名称，应该是.browserslistrc，你在issue里写的少了个s，不知道是否是这个原因

**Comment by wangqiaoling01** [comment]
哈哈 不是这个原因

**Comment by otakustay** [comment]
是否能确认下箭头函数来自哪里，来自项目源码还是哪个第三方包？
