### ISSUE TITLE
如何在finalize中正确配置webpack5的模块联邦属性

### ISSUE THREAD

**Issue by Tigerremy** [ecomfe/reskript#198]
RT

**Comment by otakustay** [comment]
往`config.plugins`里塞`ModuleFederationPlugin`就行吧，你具体遇到的错误是什么？

**Comment by Tigerremy** [comment]
> 往`config.plugins`里塞`ModuleFederationPlugin`就行吧，你具体遇到的错误是什么？

react.development.js?72d0:1309 Uncaught ScriptExternalLoadError: Loading script failed
貌似是暴露不出去组件，导致引入失败

**Comment by otakustay** [comment]
你的具体配置能贴到这边吗？包括host和remote的

**Comment by Tigerremy** [comment]
exports.build = {
    appTitle: 'emp-compontns',
    finalize: webpackConfig => {
        webpackConfig.plugins.push(new ModuleFederationPlugin({
            filename: 'mfcom.js',
            name: 'root',
            exposes: {
                './xx': './src/customComponents/ELayout/index.tsx',
            },
        }));
        return webpackConfig;
    },
};


  webpackConfig.plugins.push(
      new ModuleFederationPlugin({
          filename: 'mfcomma.js',
          name: 'mr',
          remotes: {
              one: 'root@http://localhost:8765/mfcom.js',
          },
      })
  );

const MFLayout = React.lazy(() => import('one/xx'));

 <React.Suspense fallback="loading...">
      <MFLayout />
  </React.Suspense>

**Comment by otakustay** [comment]
看上去remote的`library`没有配？同时在React项目里，恐怕还要配`shared`来共享`react`和`react-dom`等库。

你最初的`Loading script failed`错误下面有详细信息么，我找到一些类似的：https://github.com/module-federation/module-federation-examples/issues/692

**Comment by Tigerremy** [comment]
> 看上去remote的`library`没有配？同时在React项目里，恐怕还要配`shared`来共享`react`和`react-dom`等库。
> 
> 你最初的`Loading script failed`错误下面有详细信息么，我找到一些类似的：[module-federation/module-federation-examples#692](https://github.com/module-federation/module-federation-examples/issues/692)

![image](https://user-images.githubusercontent.com/29435792/142837645-e3372285-e0c5-44ea-9fad-1a65e418264c.png)
感觉和share没关系...,暂时不需要共享第三方依赖

**Comment by otakustay** [comment]
从我引用的issue来看，和qiankun是有冲突的，解决方法在issue里最后面的回复中有。如果你没有使用qiankun，恐怕得具体研究下了，我这边的上下文信息有点太少……

**Comment by Tigerremy** [comment]
> 从我引用的issue来看，和qiankun是有冲突的，解决方法在issue里最后面的回复中有。如果你没有使用qiankun，恐怕得具体研究下了，我这边的上下文信息有点太少……

好的，感谢

**Comment by Tigerremy** [comment]
![image](https://user-images.githubusercontent.com/29435792/142969556-75a49e85-724b-4c39-81b2-f1ece199ae55.png)
正常用exposes个东西出来的话会有entry.js这个文件，但是reskript没有，finalize是透传webpack的配置的吗

**Comment by Tigerremy** [comment]
finalize是透传的webpack配置吗，现在是mf的导入导出好像都不行...

**Comment by otakustay** [comment]
finalize后返回的config不会再被处理，会直接丢给webpack了

**Comment by Tigerremy** [comment]
导入mf模块，reskript报错，黔驴技穷了...,其他项目正常导入....
![image](https://user-images.githubusercontent.com/29435792/142977019-fb51bdb9-5de2-4452-9c50-b40ca2c724b4.png)
`    finalize: webpackConfig => {
        if (process.env.NODE_ENV === 'production') {
            webpackConfig.output.publicPath = '/child/micro-auth/assets/';
        }
        webpackConfig.plugins.push(
            new ModuleFederationPlugin({
                filename: 'mfcomma.js',
                name: 'mr',
                remotes: {
                    '@emp/react-project': 'empReactProject@http://localhost:8002/emp.js',
                },
            })
        );
        return webpackConfig;
    },`
