### ISSUE TITLE
npx初始化skr项目 相关文件位置不对 

### ISSUE THREAD

**Issue by heart-er** [ecomfe/reskript#206]
环境
- node  v16.8.0
- yarn   v1.22.11
- pnpm v6.17.1

如**下图一**
!!!!
!!!! yarn 和 pnpm 的项目初始化生成都是一样的问题

1. 执行 npx @reskript/init trello-app 来生成依赖
2. 相关的 node_modules, package.json, yarn.lock (pnpm.lock也是如此) 都被放置在了项目的外面
3. **如图二**，生成项目后，package.json中的依赖不全（所以即使我把 node_modules, package.json, yarn.lock (pnpm.lock) 手动移动到项目目录中也是无法执行 ）

图一
![image](https://user-images.githubusercontent.com/24717511/144957497-68b030d6-526a-4a32-966b-409ba1c8b312.png)

图二
![image](https://user-images.githubusercontent.com/24717511/144957923-86bc3c85-b0d8-49f8-88a2-4f7eb61ece10.png)

**Comment by otakustay** [comment]
@MBearo 这个问题会不会有可能是 #199 引入的？

**Comment by MBearo** [comment]
> @MBearo 这个问题会不会有可能是 #199 引入的？

#199 是修复该 issue 的，发个新版应该可以解决
