### ISSUE TITLE
windows @reskript/init 无法初始化

### ISSUE THREAD

**Issue by berwin0415** [ecomfe/reskript#239]
看了下是globby的问题

`  const files = await globby(`${templateDirectory}/**`, {dot: true});`

这段代码， windows下返回为空

see: [sindresorhus/globby#179](https://github.com/sindresorhus/globby/issues/179)

**Comment by otakustay** [comment]
要改的地方还不止这一处……

**Comment by otakustay** [comment]
帮忙试一下`3.0.3`是不是在Windows下可用

**Comment by otakustay** [comment]
`3.0.3`的实现应该是错的，试一下`3.0.4`吧，我对所有的`globby()`调用都做了处理

**Comment by berwin0415** [comment]
还有点问题， 路径无法跨盘符

**Comment by otakustay** [comment]
这就有点很麻烦了，看来不能用glob相关的库了……

**Comment by otakustay** [comment]
关于跨盘符的问题，我打算在下个大版本中再修复。当前至少cd到目录后再`npx @reskript/init .`是能用的吧？

**Comment by berwin0415** [comment]
也不行，  目标目录得和npx临时目录同一盘符

**Comment by otakustay** [comment]
OK，我再处理一下

**Comment by otakustay** [comment]
`3.0.6`应该修复了问题
