### ISSUE TITLE
eslint import-order rule 错误

### ISSUE THREAD

**Issue by HereSinceres** [ecomfe/reskript#242]
code:
```
import './a.js';
import {b} from 'antd';
```
期望无import-order 错误

**Comment by otakustay** [comment]
按照import-order的规则，第三方的包在相对路径前面，这个代码显然是应该报错的

**Comment by HereSinceres** [comment]
比如 core.js 或者一些期望一进入就开始执行的全局函数，或者是样式的最开始的顺序

**Comment by HereSinceres** [comment]
我现在vscode 使用了一个插件：
vscode import 排序插件 https://marketplace.visualstudio.com/items?itemName=amatiasq.sort-imports 
配置选择(偏好设置下Sort-imports: Default-sort-style)为：module-scoped

**Comment by otakustay** [comment]
我们的默认实现是参考[eslint-plugin-import的order规则](https://github.com/import-js/eslint-plugin-import/blob/HEAD/docs/rules/order.md)来做的，这也是社区认可最广泛的规则，对应你的插件里的style配置应该是eslint

**Comment by otakustay** [comment]
对于你提的特殊情况我承认存在问题，建议少量的可以用注释关掉。我们不打算提供module的规则，因为这个规则需要大量读取本地的`package.json`才能判断，性能上很差。我们原本自己内置这个规则，也是因为`eslint-plugin-import`性能实在太差才选择自己开发的，lint的性能相当重要

**Comment by HereSinceres** [comment]
ok，关 issue
