### ISSUE TITLE
文档网站404

### ISSUE THREAD

**Issue by whizbz11** [ecomfe/reskript#256]
<img width="1068" alt="image" src="https://user-images.githubusercontent.com/13316317/152967160-25f532b7-8935-421f-9968-d5a9e45318ca.png">
https://ecomfe.github.io/reskript/docs/getting-started

**Comment by otakustay** [comment]
从哪里获得的这个链接？我更新一下链接。当前是reskript.dev

**Comment by whizbz11** [comment]
reskript.dev可以正常访问，感谢~~
