### ISSUE TITLE
devServer增加https属性，报错

### ISSUE THREAD

**Issue by whizbz11** [ecomfe/reskript#257]
<img width="1110" alt="image" src="https://user-images.githubusercontent.com/13316317/153156948-2e320c0f-9b39-47ab-a17f-40ccc838fa02.png">
<img width="586" alt="image" src="https://user-images.githubusercontent.com/13316317/153157335-75dde5fd-0241-4e58-a764-3ef72b593122.png">

**Comment by otakustay** [comment]
你的版本大概不对，至少需要`2.5.0`以上

**Comment by whizbz11** [comment]
升级到^2.5.0好使了，想问下升级到4.X.X版本，可以平滑升级么，需要其他特殊配置么

**Comment by otakustay** [comment]
如流上找我一下，单独和你说吧

**Comment by whizbz11** [comment]
好的，感谢
