### ISSUE TITLE
使用reskript 引入 antd switch组件样式异常。

### ISSUE THREAD

**Issue by guoyong** [ecomfe/reskript#258]
在项目中引入 antd样式
`import 'antd/dist/antd.less';`

![image](https://user-images.githubusercontent.com/8455655/153202886-dd74ca22-ec70-431c-bf2f-a4600ec9bfda.png)
switch组件激活状态，样式异常。
![image](https://user-images.githubusercontent.com/8455655/153203027-972ef7f5-079e-4af0-8eeb-1db724bce19c.png)
编译产出物
![image](https://user-images.githubusercontent.com/8455655/153203485-59ef7678-982f-440d-a429-daff5e649939.png)

正常预期：
![image](https://user-images.githubusercontent.com/8455655/153203102-92af557f-efd1-4450-80ec-f5b01b6b6c2b.png)
![image](https://user-images.githubusercontent.com/8455655/153203155-48ed7ac6-1e42-4f4a-85eb-4910247f8291.png)

如果引入 antd/dist/antd.css 则样式正常。

reskript config build相关配置：
![image](https://user-images.githubusercontent.com/8455655/153204302-55ff8934-d924-45af-b064-3aa9c5685867.png)

这里less是有什么特殊处理么？
还有一个问题，为什么编译产出物是 left:80%，chrome 会解析成 left:calc(80%)？

**Comment by otakustay** [comment]
是的，和`less-plugin-functions`有冲突，reSKRipt有部分解决这问题，但应该没有完全解决，我再优化一下

**Comment by otakustay** [comment]
我在`4.1.2`中优化了处理的逻辑，预期是能覆盖所有less文件中使用`calc`的问题。

**Comment by otakustay** [comment]
不过你需要先升级4.x……升级不难，可以参考文档中的迁移手册
