### ISSUE TITLE
适配husky 5.x

### ISSUE THREAD

**Issue by otakustay** [ecomfe/reskript#26]
根据[husky 5.x升级指南](https://dev.to/typicode/what-s-new-in-husky-5-32g5)，新的配置是在`.husky`目录下的，需要新的方法去判断

**Comment by otakustay** [comment]
在 https://github.com/typicode/husky/issues/894 以前先检查`.husky`目录和下面的文件

**Comment by otakustay** [comment]
或者考虑到通用性，干脆去掉对husky的检查？

**Comment by Justineo** [comment]
Husky 5 改了 LICENSE，要收费了的吧……
