### ISSUE TITLE
环境变量配置文件加载顺序有误, local < mode，与文档不一致

### ISSUE THREAD

**Issue by yantingxi** [ecomfe/reskript#260]
![e388149f8a6f526d12e4150a78bc8538](https://user-images.githubusercontent.com/30825361/154012128-9c957eec-557f-4c5f-8d4f-4f0aa9503e59.png)
<img width="257" alt="d8b57e185419fc3a91b0f24029dc8203" src="https://user-images.githubusercontent.com/30825361/154012144-abc4e5ff-81db-41a2-a933-670e98fb462b.png">

**Comment by MBearo** [comment]
可能是文档有问题，并且和Monorepo的不一致
![image](https://user-images.githubusercontent.com/23232655/154274031-83824ca7-be6f-4a6d-94ed-2cd72b266c78.png)

**Comment by otakustay** [comment]
> 并且和Monorepo的不一致

这是因为monorepo里的那个分支用的`unshift`，越后面的排越前面

**Comment by MBearo** [comment]
> > 并且和Monorepo的不一致
> 
> 这是因为monorepo里的那个分支用的`unshift`，越后面的排越前面

所以是文档没有更新？

**Comment by otakustay** [comment]
文档是对的，代码的正常部分没有对应文档，但monorepo部分和文档是对上的。已经修复了待发布
