### ISSUE TITLE
windows环境开发问题

### ISSUE THREAD

**Issue by galileo303** [ecomfe/reskript#262]
我们使用了@reskript/plugin-workspace-no-build插件来对多包包名进行简化，但是发现在window平台会报如图所示，也就是我们在引用这些包的时候
![企业微信截图_1645169782428](https://user-images.githubusercontent.com/17979785/154642534-e1fef130-b7b0-4b31-9921-d2d7d6eef367.png)

react-refresh-webpack-plugin找不到，但是mac系统是可以正常启动和找到的。

**Comment by galileo303** [comment]
比如说我们在editor模块里面使用了hooks模块，
<img width="1062" alt="image" src="https://user-images.githubusercontent.com/17979785/154643192-4cb9f0ba-f6eb-43bd-95f2-a236c130590b.png">
mac系统中是可以运行不会报错，但是windows系统就会报错。
我们使用的pnpm作为多包项目管理。

**Comment by galileo303** [comment]
也尝试过安装依赖react-refresh-webpack-plugin，但是实际没有起到作用。还是同样报错

**Comment by otakustay** [comment]
这个问题不是`react-refresh`导致的，看起来是一些应该需要babel处理的代码没有被babel处理，是一个文件是否属于项目源码的识别有问题

**Comment by otakustay** [comment]
我看了一下实现，没找到什么头绪。你能否提供一个不会泄露业务信息的可复现的代码库给我

**Comment by galileo303** [comment]
> 这个问题不是`react-refresh`导致的，看起来是一些应该需要babel处理的代码没有被babel处理，是一个文件是否属于项目源码的识别有问题



> 我看了一下实现，没找到什么头绪。你能否提供一个不会泄露业务信息的可复现的代码库给我

好的，怎么给你们呢

**Comment by otakustay** [comment]
打zip包发到otakustay@gmail.com吧

**Comment by galileo303** [comment]
> 打zip包发到[otakustay@gmail.com](mailto:otakustay@gmail.com)吧

已发送，请查收。
<img width="1039" alt="image" src="https://user-images.githubusercontent.com/17979785/155640010-b8ca164a-5a42-4f45-8d02-ba1142349e50.png">

**Comment by galileo303** [comment]
> 打zip包发到[otakustay@gmail.com](mailto:otakustay@gmail.com)吧

<img width="575" alt="image" src="https://user-images.githubusercontent.com/17979785/155644047-ef846708-026a-406d-b630-1f55e4280a66.png">
不行啊，大佬，发不过去。
说被你们邮箱给拒绝了

**Comment by galileo303** [comment]
> 打zip包发到[otakustay@gmail.com](mailto:otakustay@gmail.com)吧

我放git上了，可以下载到本地运行下
系统环境：windows
步骤：
1、使用pnpm install 安装依赖
2、启动pnpm run start
3、打开8099端口即可复现

https://github.com/galileo303/reskriptBugDemo

**Comment by otakustay** [comment]
再问一下，你使用的命令行是什么，CMD、Windows Terminal或者其它工具？

我这边用Windows Terminal测确实发现了一些问题：

```
[ 'D:/Develop/reskriptBugDemo/packages/hooks' ]
D:\Develop\reskriptBugDemo\packages\hooks\src\useToggler.ts
```

看起来路径的分隔符是不一样的，我会修复一下这个问题。保守起见我也希望在你用的命令行工具里再测一下

**Comment by galileo303** [comment]
> 再问一下，你使用的命令行是什么，CMD、Windows Terminal或者其它工具？
> 
> 我这边用Windows Terminal测确实发现了一些问题：
> 
> ```
> [ 'D:/Develop/reskriptBugDemo/packages/hooks' ]
> D:\Develop\reskriptBugDemo\packages\hooks\src\useToggler.ts
> ```
> 
> 看起来路径的分隔符是不一样的，我会修复一下这个问题。保守起见我也希望在你用的命令行工具里再测一下

cmd 和 Terminal，还有windows shell 都有。
表现都一样。

谢谢希望尽快修复

**Comment by otakustay** [comment]
我在`4.2.1`版本中修复了这个问题，但是你的版本是3.x比较老，所以我发了 https://github.com/galileo303/reskriptBugDemo/pull/1 做升级，辛苦你参考这个PR把版本和配置文件做一下升级就可以使用。我已经在Windows 11 + Windows Terminal/CMD下测试过

**Comment by otakustay** [comment]
另外你的项目还有些问题，比如没有安装`webpack`和`typescript`之类的，我也在上面的PR里一起修改了

**Comment by galileo303** [comment]
> 另外你的项目还有些问题，比如没有安装`webpack`和`typescript`之类的，我也在上面的PR里一起修改了

谢谢，但是我看到合并过来的有个setting包，里面写死了启动端口。
<img width="1068" alt="image" src="https://user-images.githubusercontent.com/17979785/155918202-b41b77ae-63cf-4ff7-9879-39366a35acf4.png">

目前启动短裤都变成了8788，无法更改了。大佬顺带也看下

**Comment by otakustay** [comment]
应该不会有这个问题，你可以看到这个代码最下面有`...settings`，即你自己的`devServer.port`配置会覆盖这个默认值。我跑了一下你的示例代码库，确实可以通过8099端口访问
