### ISSUE TITLE
assets 资源路径失效

### ISSUE THREAD

**Issue by galileo303** [ecomfe/reskript#267]
<img width="862" alt="image" src="https://user-images.githubusercontent.com/17979785/156093722-c3e1d069-6a3c-4a3e-b96f-5ef519b82227.png">

assets 资源路径失效了，v3版本是可以加载到js资源，v4版本后就全部加载的是路由了。没有assets 资源了。但是文档没有变。

<img width="532" alt="image" src="https://user-images.githubusercontent.com/17979785/156093913-cadfd4f1-6ae8-4b97-b3c5-93c38f9e1c24.png">
加载出来是html了，而不是js了

**Comment by otakustay** [comment]
3003端口是你的父应用还是子应用的？

**Comment by galileo303** [comment]
> 3003端口是你的父应用还是子应用的？

我用的ModuleFederationPlugin 打包的3003的 remotejs资源。但是3003不知道怎么去拿这个js资源，v4里面会吧这个资源给我重定向到html

**Comment by galileo303** [comment]
> > 3003端口是你的父应用还是子应用的？
> 
> 我用的ModuleFederationPlugin 打包的3003的 remotejs资源。但是3003不知道怎么去拿这个js资源，v4里面会吧这个资源给我重定向到html

之前v3版本，我们是可以通过http://localhost:3003/assets/* 去拿到3003的js资源文件的

**Comment by otakustay** [comment]
你先用`skr build`跑一下构建，看构建完后有没有`dist/assets/remoteEntry.js`这个文件，如果有的话，理论上`skr dev`也一定有这个文件，V4版本和V3版本这一块的逻辑没有做任何的变动，我们也有V4 + ModuleFederation的使用场景

另外，如果的3003端口是ModuleFederation的提供方，那么它需要用`skr dev --host=localhost`启动。消费方需要用`http://localhost:3003/assets/remoteEntry.js`作为`remotes`的配置

**Comment by galileo303** [comment]
> 你先用`skr build`跑一下构建，看构建完后有没有`dist/assets/remoteEntry.js`这个文件，如果有的话，理论上`skr dev`也一定有这个文件，V4版本和V3版本这一块的逻辑没有做任何的变动，我们也有V4 + ModuleFederation的使用场景
> 
> 另外，如果的3003端口是ModuleFederation的提供方，那么它需要用`skr dev --host=localhost`启动。消费方需要用`http://localhost:3003/assets/remoteEntry.js`作为`remotes`的配置

是的，我们是用`skr dev --host=localhost`启动的。
刚才试了下，确实没有build出来remoteEntry.js
难道我们这么配置不对？但是也没有报错。
<img width="1244" alt="image" src="https://user-images.githubusercontent.com/17979785/156101548-eb03169a-9119-4e16-9421-2ba29884a841.png">

V4 + ModuleFederation 大佬是怎么结合的？

**Comment by galileo303** [comment]
> > 你先用`skr build`跑一下构建，看构建完后有没有`dist/assets/remoteEntry.js`这个文件，如果有的话，理论上`skr dev`也一定有这个文件，V4版本和V3版本这一块的逻辑没有做任何的变动，我们也有V4 + ModuleFederation的使用场景
> > 另外，如果的3003端口是ModuleFederation的提供方，那么它需要用`skr dev --host=localhost`启动。消费方需要用`http://localhost:3003/assets/remoteEntry.js`作为`remotes`的配置
> 
> 是的，我们是用`skr dev --host=localhost`启动的。 刚才试了下，确实没有build出来remoteEntry.js 难道我们这么配置不对？但是也没有报错。 <img alt="image" width="1244" src="https://user-images.githubusercontent.com/17979785/156101548-eb03169a-9119-4e16-9421-2ba29884a841.png">
> 
> V4 + ModuleFederation 大佬是怎么结合的？

原先v3一样的配置，是可以打包出来的，v4就没有打包出来了。怀疑是不是configure做了什么

**Comment by otakustay** [comment]
我看你截图里的代码，这个`new ModuleFederationPlugin()`后没有push到`plugins`里去，会是这个原因吗？
