### ISSUE TITLE
在路由懒加载场景中，使用antd优化，发现antd的样式会覆盖定制的样式，有什么好的方案规避么？

### ISSUE THREAD

**Issue by whizbz11** [ecomfe/reskript#276]
现有问题：
复写按钮的样式，在路由懒加载场景中，在点击第二个路由的时候才会加载还有按钮的组件，这个时候才会加载antd自己的默认的按钮的样式。这个时候默认的样式会影响到复写的样式，有什么好的解决方案么？

想过几个解决方案：
1、提高自己写按钮样式的作用域（感觉不灵活不方便其他项目的公共）
2、antd样式一次性加载，不使用优化，再加载复写的样式，这样可以解决，但打出的包会变大

**Comment by otakustay** [comment]
参考 #214 把整个antd的优化关掉自己来
