### ISSUE TITLE
*.var.less 在 5.x 版本中失效

### ISSUE THREAD

**Issue by LeuisKen** [ecomfe/reskript#279]
复现步骤：

- 使用 @reskript/init 创建新项目
- 按照如下方式创建 utils.var.less 并在 app.global.less 中引入

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/7701575/158021695-8d1385b9-c6a9-40f1-b799-7a96ef222222.png">

**Comment by otakustay** [comment]
5.2.0
