### ISSUE TITLE
构建开启antd优化的话 引入antd的locale会有问题

### ISSUE THREAD

**Issue by btnkr** [ecomfe/reskript#289]
`import zhCN from 'antd/lib/locale/zh_CN';`

![cb7d979c1754e22a32f68d35612bea48](https://user-images.githubusercontent.com/46664126/165883396-3e3607ef-62a4-4f82-82e7-92e97b31b7ae.png)

**Comment by otakustay** [comment]
你的问题是引入字段还是引入antd的locale？从报错的信息来看似乎没有和字体有关的东西……

**Comment by otakustay** [comment]
没注意到你修改了标题。你能提供一下你使用的版本和配置吗？看起来是用Vite构建的？

**Comment by btnkr** [comment]
<img width="349" alt="image" src="https://user-images.githubusercontent.com/46664126/176579367-acfee703-8b40-46b2-aa6a-f29af159e88a.png">

**Comment by otakustay** [comment]
我试了一下，你把`antd/lib/locale/zh_CN`改成`antd/es/locale/zh_CN`（`lib`换成`es`）应该能解决问题

建议所有antd的东西都从`antd/es`里弄，这个是ESM的

**Comment by btnkr** [comment]
> 我试了一下，你把`antd/lib/locale/zh_CN`改成`antd/es/locale/zh_CN`（`lib`换成`es`）应该能解决问题
> 
> 建议所有antd的东西都从`antd/es`里弄，这个是ESM的

好使啦！太感谢啦！
