### ISSUE TITLE
引入 XX.svg?react 导致报错，无法转换成组件

### ISSUE THREAD

**Issue by galileo303** [ecomfe/reskript#291]
引入 XX.svg?react 导致报错，无法转换成组件
![image](https://user-images.githubusercontent.com/17979785/171013234-1f52e7e5-feb7-4332-9a73-e3adfca6699a.png)
引入方式：
<img width="436" alt="image" src="https://user-images.githubusercontent.com/17979785/171013539-e6cbb6cf-9718-400f-8cd1-0ac7c50c434f.png">
依赖
    "@babel/core": "7.16.7",
    "@reskript/cli": "4.2.1",
    "@reskript/cli-build": "4.2.1",
    "@reskript/cli-dev": "4.2.1",
    "@reskript/cli-lint": "4.2.1",
    "@reskript/cli-test": "4.2.1",
    "@reskript/config-webpack": "4.2.1",
    "@reskript/plugin-sass": "4.2.1",
    "@reskript/plugin-workspace-no-build": "4.2.1",
    "@reskript/settings": "4.2.1",
    "@types/react": "^17.0.38",
    "@types/react-dom": "^17.0.11",
    "core-js": "3.20.2",
    "eslint": "8.6.0",
    "external-remotes-plugin": "^1.0.0",
    "husky": "^7.0.4",
    "stylelint": "^14.5.3",
    "typescript": "^4.5.5",
    "webpack": "^5.69.1"

**Comment by otakustay** [comment]
辛苦提供一下你的svg文件的内容

**Comment by galileo303** [comment]
> 辛苦提供一下你的svg文件的内容
![module](https://user-images.githubusercontent.com/17979785/171341484-85668a2d-def3-420e-8aa4-470a1f0434e4.svg)
