### ISSUE TITLE
reskript 引入 qiankun插件编译报错

### ISSUE THREAD

**Issue by guoyong** [ecomfe/reskript#295]
加入qiankun插件前，编译正常。加入后报错，无其他提示。。
<img width="657" alt="image" src="https://user-images.githubusercontent.com/8455655/174525287-4997a63e-a943-4dcc-98be-358700cd83db.png">

编译配置如下
import {configure} from '@reskript/settings';
import qiankun = require('@reskript/plugin-qiankun');

import build from '../build.config';

export default configure(
    'webpack',
    {
        build,
        plugins: [
            qiankun('micAppXbrain'),
        ],
    }
);

build.config

import path from 'path';
import CopyPlugin from 'copy-webpack-plugin';
import {FinalizableWebpackConfiguration, WebpackBuildEntry, BuildInternals} from '@reskript/settings';

import {SOURCE_PATH, DIST_PATH, PUBLIC_PATH} from './paths';

export default {
    appTitle: '百度自动驾驶云',
    reportLintErrors: false,
    finalize: async (
        webpackConfig: FinalizableWebpackConfiguration, buildEntry: WebpackBuildEntry, internals: BuildInternals
    ) => {
        const isProduct = webpackConfig.mode !== 'development';
        const loadingRules = [
            internals.rules.script(buildEntry),
            internals.rules.less(buildEntry),
            internals.rules.css(buildEntry),
            internals.rules.svg(buildEntry),
            internals.rules.file(buildEntry),
        ] as const;

        const builtinRules = await Promise.all(loadingRules);

        webpackConfig.module.rules = [
            ...builtinRules,
            // 不修改静态资源名称、编译后直接覆盖替换
            {
                test: /\.(jpe?g|png|webp)$/i,
                use: {
                    loader: 'file-loader',
                    options: {
                        outputPath: 'images',
                    },
                },
            },
        ];

        if (isProduct) {
            webpackConfig.output.publicPath = PUBLIC_PATH;
            webpackConfig.module.rules.push({
                test: /\.json?$/,
                exclude: /node_modules/,
                use: [{
                    loader: 'string-replace-loader',
                    options: {
                        search: '//at.alicdn.com/t/',
                        replace: `${PUBLIC_PATH}font/`,
                        flags: 'g',
                    },
                }],
            });
            webpackConfig.plugins.push(
                new CopyPlugin({
                    patterns: [{
                        from: path.resolve(SOURCE_PATH, 'assets/font'),
                        to: path.resolve(DIST_PATH, 'assets/font'),
                        noErrorOnMissing: true,
                    }],
                })
            );
            webpackConfig.optimization = {
                minimize: true,
                usedExports: true,
                splitChunks: {
                    automaticNameDelimiter: '~',
                    cacheGroups: {
                        react: {
                            name: 'react',
                            test: /[\\/]node_modules[\\/]_?react(.*)/,
                            priority: 3,
                            chunks: 'all',
                        },
                        echarts: {
                            name: 'echarts',
                            test: /[\\/]node_modules[\\/]_?echarts(.*)/,
                            priority: 3,
                            chunks: 'all',
                        },
                        zrender: {
                            name: 'zrender',
                            test: /[\\/]node_modules[\\/]_?zrender(.*)/,
                            priority: 3,
                            chunks: 'all',
                        },
                        antd: {
                            name: 'antd',
                            test: /\/node_modules\/(antd|@ant(.*))\//,
                            priority: 3,
                            chunks: 'all',
                        },
                        libs: {
                            name: 'libs',
                            test: /[\\/]node_modules[\\/]/,
                            priority: 2,
                            chunks: 'all',
                        },
                        common: {
                            name: 'common',
                            chunks: 'all',
                            minChunks: 2,
                        },
                    },
                },
            };
        }
        return webpackConfig;
    },
    inspect: {
        /** 初始资源检查 */
        initialResources: {
            count: ['error', 6],
            totalSize: ['error', 2 * 1024 * 1024],
            sizeDeviation: ['error', 0.2],
            disallowImports: ['error', []],
        },
        /** 检查重复引入的第三方库 */
        duplicatePackages: ['warn', {excludes: ['tslib', 'eslint-*']}],
        // 微前端入口检查，详见 https://reskript.dev/docs/settings/build 末尾
        htmlImportable: 'error',
    },
    uses: [],
} as any;

相关版本如下：
    "@reskript/cli": "5.2.1",
    "@reskript/cli-build": "5.2.1",
    "@reskript/cli-dev": "5.2.1",
    "@reskript/cli-lint": "5.2.1",
    "@reskript/config-lint": "5.2.1",
    "@reskript/plugin-qiankun": "^5.3.0"

**Comment by otakustay** [comment]
用`SKR_LOGGING=debug skr dev`跑一下看下输出的错误
