### ISSUE TITLE
reskript/settings : configure options plugins interface error

### ISSUE THREAD

**Issue by antupwork** [ecomfe/reskript#308]
TS2769: No overload matches this call.   Overload 1 of 2, '(driver: "webpack", settings: WebpackUserSetting): UserSettings', gave the following error.
 Overload 2 of 2, '(driver: "vite", settings: ViteUserSetting): UserSettings', gave the following error.     Argument of type '"webpack"' is not assignable to parameter of type '"vite"'.

**Comment by MBearo** [comment]
补充一下，inject-html插件类型问题。
![4bd67c8674c325343a09641aaa75b694](https://user-images.githubusercontent.com/23232655/183655279-96ce7c50-b69e-4c07-803c-98b88a0dabe3.jpg)

**Comment by otakustay** [comment]
提供一下各个reskript包的版本，它们是否版本一致？

**Comment by antupwork** [comment]
> 提供一下各个reskript包的版本，它们是否版本一致？

 "@reskript/cli": "5.4.0",
    "@reskript/cli-build": "5.4.0",
    "@reskript/cli-dev": "5.4.0",
    "@reskript/cli-lint": "5.4.0",
    "@reskript/config-lint": "5.4.0",
    "@reskript/plugin-inject-html": "^5.6.0",

**Comment by MBearo** [comment]
> > 提供一下各个reskript包的版本，它们是否版本一致？
> 
> "@reskript/cli": "5.4.0", "@reskript/cli-build": "5.4.0", "@reskript/cli-dev": "5.4.0", "@reskript/cli-lint": "5.4.0", "@reskript/config-lint": "5.4.0", "@reskript/plugin-inject-html": "^5.6.0",

保持版本一致试一下？

**Comment by antupwork** [comment]
> 

plugin-inject-html切换到5.4.0 可以了
