### ISSUE TITLE
css calc 方法编译错误

### ISSUE THREAD

**Issue by antupwork** [ecomfe/reskript#309]
`
// 相关版本
{"@reskript/cli": "5.4.0", "@reskript/cli-build": "5.4.0", "@reskript/cli-dev": "5.4.0", "@reskript/cli-lint": "5.4.0", "@reskript/config-lint": "5.4.0", "@reskript/plugin-inject-html": "5.4.0",}
`
问题详述：
css calc方法，在less loader 编译后导致句柄异常
 源码：
<img width="361" alt="image" src="https://user-images.githubusercontent.com/17873074/183817475-ed3de807-bfb2-4abd-983c-34910c87ad6a.png">
编译后：
<img width="1179" alt="image" src="https://user-images.githubusercontent.com/17873074/183817568-b0e3801f-7cbc-483a-bc30-145c87323057.png">
尝试解决：

- 单引号 替换 为双引号 ，可以解决
- 句柄 calc(~ '100vh - 160px') 去掉~后空格 calc(~'100vh - 160px')，可以解决
- 句柄 calc(~ '100vh - 160px') 写法替换为 '~calc( 100vh - 160px)'，可以解决

**Comment by antupwork** [comment]
补充：
该情况下，尝试解决办法均失效
源码：
<img width="545" alt="image" src="https://user-images.githubusercontent.com/17873074/183819241-11e3b376-fdda-4a54-ba77-b3edd62a2458.png">
编辑error：
<img width="1339" alt="image" src="https://user-images.githubusercontent.com/17873074/183819296-e41742d7-f4de-49cd-9fa4-087790a9bffa.png">

**Comment by otakustay** [comment]
尝试一下5.6.1版本，补了[2个用例](https://github.com/ecomfe/reskript/blob/5a3b7eb136be08d85ec8af94d6a60dd7cc9bd1d4/packages/build-utils/src/config/less/__tests__/safeLess.test.ts#L60-L68)
