### ISSUE TITLE
margin-inline-XXX等属性编译后丢失

### ISSUE THREAD

**Issue by SimpleQu** [ecomfe/reskript#311]
antd中select组件的属性编译后丢失，目前验证与antd的版本关系应该不大，截图信息如下：

1. 正常展示
<img width="1353" alt="image" src="https://user-images.githubusercontent.com/22764514/185557571-20a637d5-d2b5-4d71-a5d0-df94766db6df.png">

2. 编译后异常展示
<img width="1437" alt="image" src="https://user-images.githubusercontent.com/22764514/185558286-4308b676-ca3c-4b36-9210-266fd441c168.png">

其中antd的版本是v4.22.6，查看源码该属性在源码中是存在，有可能是编译后导致丢失

**Comment by otakustay** [comment]
你配置的浏览器兼容性太老，postcss把它编译成`margin-left`和`margin-right`了，解决办法有2个：

1. 修改`.browserslistrc`，写个高点的版本，具体看caniuse哪些浏览器支持`inline-margin-start`
2. 如果你自己有HTML模板，在`<body>`或`<html>`上加个`dir="ltr"`属性就行。如果没有模板，用最新的skr已经默认加了这个

**Comment by SimpleQu** [comment]
1. `.rowserslistrc`的版本设置如下，满足要求：
```
> 0.2%
last 2 versions
Firefox ESR
not dead
```

2. 目前使用skr的是最新版本`v5.6.0`

**Comment by SimpleQu** [comment]
1. `.browserslistrc`的版本设置如下，满足要求：
```
> 0.2%
last 2 versions
Firefox ESR
not dead
```
2. 没有配置自己的THTML模版，目前使用skr的是最新版本v5.6.0

**Comment by otakustay** [comment]
你看下生成的HTML里是不是有`<html dir="ltr">`这一段，postcss会把`inline-margin-start`编译成`[dir="ltr"] { margin-left }`，应该在样式上是能找到的

**Comment by otakustay** [comment]
你看下生成的HTML里是不是有`<html dir="ltr">`这一段，postcss会把`inline-margin-start`编译成`[dir="ltr"] { margin-left }`，应该在样式上是能找到的

**Comment by otakustay** [comment]
或者你认为antd的样式本身就兼容了你的浏览器，那`.browserslistrc`改成`inline-margin-start`的最小要求是最合适的

**Comment by SimpleQu** [comment]
又试了一下，因为本地开发启动qiankun-plugin的缘故导致：
1. qiankun插件模式下，生成的html没有对应的dir="ltr"
2. 非qiankun模式的HTML模板有<html dir="ltr">这段

**Comment by otakustay** [comment]
那只能你自己加一下了……
