### ISSUE TITLE
上游依赖安全漏洞

### ISSUE THREAD

**Issue by MBearo** [ecomfe/reskript#313]
@reskript/build-utils 依赖了 proxy-agent@^5.0.0，上游有使用 vm2@3.9.8

https://github.com/patriksimek/vm2/security/advisories/GHSA-mrgp-mrhc-5jrq

**Comment by otakustay** [comment]
这玩意，我试了下删掉lock文件重新install一下，就能解决了，似乎也不用我这里咋整
