### ISSUE TITLE
jest 版本升级

### ISSUE THREAD

**Issue by dongggcom** [ecomfe/reskript#317]
https://jestjs.io/docs/28.x/upgrading-to-jest28#custom-environment

依赖有 jest-environment-jsdom 的库会因为 skr test 中的 jest 不一致导致运行失败。
错误提示：
```
TypeError: Cannot read properties of undefined (reading 'testEnvironmentOptions')
```

**Comment by otakustay** [comment]
jest再往上升就没有jsdom了，会变成breaking change，所以现在卡在27版本没动，要使用skr test的话，jest同样要装到27
