### ISSUE TITLE
本地运行dev环境报错

### ISSUE THREAD

**Issue by jiushiwoyuze** [ecomfe/reskript#319]
vite模式下报错
<img width="773" alt="8715ef3d5b2e11550cd6c4958a34be58" src="https://user-images.githubusercontent.com/5416077/203229414-7f361bf1-bb29-45e5-86bf-14ae2d345b4c.png">

webpack模下报警告，但可以正常运行
<img width="981" alt="9ab6053c0310e2bc74db9243d925bcbc" src="https://user-images.githubusercontent.com/5416077/203229628-95e4d540-a4f0-4def-a263-56c5b3844608.png">

**Comment by otakustay** [comment]
[marked.esm.js](https://unpkg.com/marked@4.2.3/lib/marked.esm.js)是没有`export default`的，确实不能这么用
