### ISSUE TITLE
支持近前缀设置devServer的代理

### ISSUE THREAD

**Issue by otakustay** [ecomfe/reskript#32]
但这容易和`defaultProxyDomain`参数冲突，所以考虑增加一个`proxyRewrite`配置，可以使用对象的形式：

```js
proxyRewrite: {
  '/xxx': 'remote-host.com/yyy',
}
```

`proxyRewrite`会优先于`apiPrefixes`处理，本身有完整的代理配置能力。在`apiPrefixes`中但没有在`proxyRewrite`中的，走`defaultProxyDomain`

**Comment by otakustay** [comment]
但这个配置不打算接受完整的webpack的`proxy`配置，只做路径的rewrite就行

**Comment by daxuewen** [comment]
可以满足需求。后端服务是微服务的形式时，这个需求比较强烈。

**Comment by otakustay** [comment]
我此前不做这事，是因为这和我们理想的最终状态是相悖的。

在理想状态下，本地环境应该和实际部署环境有更高的一致性。通常在部署环境里，是有一个流量接入的服务的（nginx或者其它形式），所以我认为更合理的形式是这个流量接入服务可以在本地启动，devServer的代理到这个服务，由这个服务使用统一的配置去分到多个微服务上。

这种形式下，就有服务发现、自动代理配置这些能力，而放进devServer的配置里就是纯手工活，且可能和不同的人联调都要修改配置文件，一改编译缓存就失效
