### ISSUE TITLE
直接使用antdesign5.x的AutoComplete组件时有点问题

### ISSUE THREAD

**Issue by ilwww** [ecomfe/reskript#322]
- 问题描述：
antd升级v5，需要移除babel-plugin-import，而skr默认有antd优化（uses: ['antd', 'lodash']），使用了babel-plugin-import，然后直接使用antd@5.x的AutoComplete组件时，编译报错。
现在需要手动把配置项改为uses: ['lodash']，可正常运行。
- 当前版本：
reskript@5.7.4
antd@5.2.3
- 有用的链接：
antd 参考升级: https://ant.design/docs/react/migration-v5-cn#%E7%A7%BB%E9%99%A4-babel-plugin-import
- 相关截图：
<img width="565" alt="image" src="https://user-images.githubusercontent.com/65108179/221736805-1809f52d-f8ab-49a5-8881-2d683637fc37.png">

**Comment by otakustay** [comment]
是的，相应的版本放在6.x分支上，在等社区几个PR合并

**Comment by ilwww** [comment]
close
