### ISSUE TITLE
修改publicPath为'/'不生效，目前是'/assets'

### ISSUE THREAD

**Issue by hnyysly** [ecomfe/reskript#324]

**Comment by otakustay** [comment]
6.0会修复这个问题（已经开发尾声了），5.x无法没有breaking的情况下解决这个

**Comment by hnyysly** [comment]
这个6.0是什么时候发布了，着急等着用

**Comment by otakustay** [comment]
你可以先装`6.0.0-beta.3`，功能和变更都在里面了，后面主要是文档之类的工作，具体变更参考这里：https://github.com/ecomfe/reskript/blob/v6/site/docs/migration/v6.md

重点小心Webpack产出结构和Antd支持的变化
