### ISSUE TITLE
@babel/helper-compilation-targets: 'opera_mobile' is not a valid target

### ISSUE THREAD

**Issue by LIU-CONG-OLD** [ecomfe/reskript#333]
update pagekage but error
{
    "devDependencies": {
-        "@reskript/cli": "5.7.4",
-        "@reskript/cli-build": "5.7.4",
-        "@reskript/cli-dev": "5.7.4",
-        "@reskript/cli-lint": "5.7.4",
-        "@reskript/cli-play": "5.7.4",
-        "@reskript/cli-test": "5.7.4",
-        "@reskript/config-lint": "5.7.4",
+        "@reskript/cli": "6.0.0",
+        "@reskript/cli-build": "6.0.0",
+        "@reskript/cli-dev": "6.0.0",
+        "@reskript/cli-lint": "6.0.0",
+        "@reskript/cli-play": "6.0.0",
+        "@reskript/cli-test": "6.0.0",
+        "@reskript/config-lint": "6.0.0",
+        "@reskript/settings": "6.0.0",
    }
}

why
@babel/helper-compilation-targets: 'opera_mobile' is not a valid target
- Did you mean 'opera'? (While processing: "base$0$16")
    at Generator.next (<anonymous>)
    at Generator.next (<anonymous>)
    at Generator.next (<anonymous>)
    at Generator.next (<anonymous>)
    at cachedFunction.next (<anonymous>)
    at loadPluginDescriptor.next (<anonymous>)
    at loadPluginDescriptors.next (<anonymous>)
    at Generator.next (<anonymous>)
    at loadFullConfig.next (<anonymous>)
    at transform.next (<anonymous>)

**Comment by LIU-CONG-OLD** [comment]
为什么无法启动

**Comment by otakustay** [comment]
我看了[browserslist支持的浏览器](https://github.com/browserslist/browserslist#browsers)，确实是没有`opera_mobile`这个东西的，应该是`op_mob`才对

**Comment by LIU-CONG-OLD** [comment]
> 我看了[browserslist支持的浏览器](https://github.com/browserslist/browserslist#browsers)，确实是没有`opera_mobile`这个东西的，应该是`op_mob`才对

**Comment by LIU-CONG-OLD** [comment]
请问我可以怎么改这个错误

**Comment by otakustay** [comment]
把`opera_mobile`改成`op_mob`，大概在你的`.browserslistrc`文件里？

**Comment by otakustay** [comment]
如果没在那的话，可能是其它地方错误，你删掉lock文件重新安装一下会不会好呢

**Comment by LIU-CONG-OLD** [comment]
没有lock文件

**Comment by otakustay** [comment]
把你的完整`package.json`发这边，我看看安装会怎么样吧

**Comment by LIU-CONG-OLD** [comment]
{
    "name": "srvinfo-web",
    "version": "0.0.1",
    "description": "查询服务器状态的小工具",
    "scripts": {
        "start": "skr dev",
        "build": "skr build --clean",
        "lint": "skr lint --strict",
        "lint-staged": "npm run lint -- --staged"
    },
    "repository": {
        "type": "git",
        "url": "ssh://hudingyuan@icode.baidu.com:8235/baidu/sysnoc/srvinfo-web"
    },
    "author": "hudingyuan",
    "license": "UNLICENSED",
    "dependencies": {
        "antd": "^5.3.2",
        "axios": "^1.3.4",
        "copy-to-clipboard": "^3.3.3",
        "react": "^17.0.2",
        "react-activation": "^0.12.2",
        "react-dom": "^17.0.2",
        "react-router-dom": "^6.2.1"
    },
    "devDependencies": {
        "@reskript/cli": "6.0.0",
        "@reskript/cli-build": "6.0.0",
        "@reskript/cli-dev": "6.0.0",
        "@reskript/cli-lint": "6.0.0",
        "@reskript/cli-play": "6.0.0",
        "@reskript/cli-test": "6.0.0",
        "@reskript/config-lint": "6.0.0",
        "@reskript/settings": "6.0.0",
        "@types/react": "^17.0.16",
        "@types/react-dom": "^17.0.9",
        "core-js": "^3.21.1",
        "eslint": "^8.11.0",
        "husky": "^4.3.8",
        "stylelint": "^15.0.0",
        "typescript": "^4.6.2",
        "webpack": "^5.70.0"
    },
    "husky": {
        "hooks": {
            "pre-commit": "npm run lint-staged"
        }
    }
}

**Comment by otakustay** [comment]
<img width="1145" alt="CleanShot 2023-07-05 at 16 09 15@2x" src="https://github.com/ecomfe/reskript/assets/639549/05131ccc-126f-4859-8c7c-d5ca8e6c0257">
我倒j是能安装成功，是不是删了node_modules和有可能有的lock文件，然后确定下node/npm版本，干净地install一次试试

**Comment by LIU-CONG-OLD** [comment]
我也能install成功。我指的是 我install之后，yarn start，失败了，然后报那个错

**Comment by otakustay** [comment]
直接内部聊天工具里，找我把代码发我试试算了

**Comment by LIU-CONG-OLD** [comment]
我这次删了yarn.lock. node_modules，重新install了一下，可以了，感谢🙏

**Comment by Gao-sy** [comment]
楼主，你还改其他地方了嘛，我试了下还是不行呢

**Comment by LIU-CONG-OLD** [comment]
> 楼主，你还改其他地方了嘛，我试了下还是不行呢

没有改别的地方，就是删了yarn.lock. node_modules，重新install了一下。package,改了

**Comment by Gao-sy** [comment]
使了好几回还是不行，后来重新创建的时候选用了umi4，发现可以启动了
