### ISSUE TITLE
纯 vite 部分使用 reskript 包时报错

### ISSUE THREAD

**Issue by dancerphil** [ecomfe/reskript#334]
## 问题

尝试使用 **`纯vite`** 接 `dev-login` 插件，使用到了 `@reskript/portal`，但是报错显示：

```
failed to load config from /Users/.../vite.config.ts
下午5:43:25 [vite] require() of ES Module /Users/.../node_modules/@reskript/portal/dist/index.js from /Users/.../vite.config.ts not supported.
Instead change the require of index.js in /Users/.../vite.config.ts to a dynamic import() which is available in all CommonJS modules.
下午5:43:25 [vite] server restart failed
```

看起来好像识别成了 cjs。

## 当前解决方案

复制 `@reskript/portal` 的源码至本地，改变 import 语句为：

`import {createPortal, router} from './scripts/portal';`

可以成功运行。

## 期望
`import {createPortal, router} from '@reskript/portal';`

**Comment by otakustay** [comment]
啥版本……我记得`@reskript/portal`一直是个纯ESM的包啊……可能是用了express router影响的？

**Comment by dancerphil** [comment]
Add `"type": "module"` in `package.json` will solve
