### ISSUE TITLE
怎样配置不拆包，打包成一个文件

### ISSUE THREAD

**Issue by hy993658052** [ecomfe/reskript#336]
在index.config.ts中配置了filename，但是打包出来除了该文件，还有两个带hash名的文件，怎样能只打包出一个文件？
<img width="311" alt="image" src="https://github.com/ecomfe/reskript/assets/33488114/a597ccb9-1dce-4530-a46d-68787d46762f">

**Comment by otakustay** [comment]
感觉是你代码里用了`await import()`导致的code splitting，检查一下？必要的话得用Webpack的插件控制：https://stackoverflow.com/questions/62048737/how-do-i-disable-webpack-4-code-splitting

**Comment by hy993658052** [comment]
感谢，已经解决了，route那里用了lazy导致的，去掉了就可以了
