### ISSUE TITLE
cli-babel 名为 no-polyfill 的参数，在代码中取值为 polyfill

### ISSUE THREAD

**Issue by MBearo** [ecomfe/reskript#340]
文档有问题，还是代码中命名有问题？
https://github.com/ecomfe/reskript/blob/2883bd8db92a61a34d0f07e09607be98fa3abb73/site/docs/cli/babel.md?plain=1#L13

**Comment by otakustay** [comment]
CLI的参数解析就有这功能，boolean类型的支持`--no-xxx`形式。从用户侧的表达来说，开polyfill是默认的，指定不用polyfill的情况更符合参数的使用，文档上就这么写
