### ISSUE TITLE
端口号冲突时自动尝试了下一个端口号，但是控制台提示有误

### ISSUE THREAD

**Issue by maaye3210** [ecomfe/reskript#344]
<img width="761" alt="image" src="https://github.com/ecomfe/reskript/assets/97799606/da5c4ca0-cff6-4bc7-93a6-bf7f0e9518db">
如图所示

**Comment by otakustay** [comment]
我不记得skr有这个功能，不知道咋来的了……控制台的提示就只认了传进来的port，没做处理

**Comment by otakustay** [comment]
这个功能是vite带的，新版本中我禁用了这个功能保持行为一致，后续再研究下怎么统一提供这能力
