### ISSUE TITLE
执行“skr lint --strict”指令提示“Command failed”（6.2.1）

### ISSUE THREAD

**Issue by SongYaoLynn** [ecomfe/reskript#357]
版本：
`"@reskript/cli": "6.2.1",
        "@reskript/cli-build": "6.2.1",
        "@reskript/cli-dev": "6.2.1",
        "@reskript/cli-lint": "6.2.1",
        "@reskript/config-lint": "6.2.1",
        "@reskript/settings": "6.2.1",`

**Comment by 123jiacheng123** [comment]
你这个问题解决了吗？突然我的lint 也无法执行了

**Comment by otakustay** [comment]
用`SKR_LOGGING=debug skr lint`跑一下看看什么错误，同时确认下你的eslint是啥版本？
