### ISSUE TITLE
期望能自动管理多个单页应用

### ISSUE THREAD

**Issue by superw-123** [ecomfe/reskript#36]
自动寻找pages目录（目录名是自定义的）下的所有目录，每一个目录都是一个单页应用，然后把对应的入口自动加到entry中

**Comment by otakustay** [comment]
最终的效果和现在`src/entries/*`是一样的，但在主观的理解上确实存在2种情况：

1. 一个基本是单页的应用，有少量的入口页，且这些页大量复用组件。此时会被认知为`src/entries`提供若干个入口，主要逻辑都在`src/components`下的共享组件中
2. 应用本身是多页，页和页之间有比较强的隔离感，仅少量通用组件。此时更多被认知为`src/pages/*`，每一个页是独立存在的。

但在程序上，他们确实是一回事，都表示`entry`有多个。因此我的计划是这样：

1. 增加一个`build.entries`配置，默认为`entries`，可以设定为`pages`
2. 对于所有的入口，统一逻辑：
    1. 目录下的`*.js`和`*/index.js`（ts、tsx、jsx同理）都认为是一个入口
    2. 目录下的`*.config.js`和`*/config.js`都认为是配置
    3. 目录下的`*.ejs`和`*/index.ejs`都认为是HTML模板

按照上面的逻辑，可以保持默认情况和现在完全一样，但支持常见的`pages`寻找入口。`pages/*`会变成`*-stable.html`、`*-insiders.html`这样的产出

@superw-123 看下这样是否可行，你对output有没有特殊的要求

**Comment by superw-123** [comment]
> 最终的效果和现在`src/entries/*`是一样的，但在主观的理解上确实存在2种情况：
> 
> 1. 一个基本是单页的应用，有少量的入口页，且这些页大量复用组件。此时会被认知为`src/entries`提供若干个入口，主要逻辑都在`src/components`下的共享组件中
> 2. 应用本身是多页，页和页之间有比较强的隔离感，仅少量通用组件。此时更多被认知为`src/pages/*`，每一个页是独立存在的。
> 
> 但在程序上，他们确实是一回事，都表示`entry`有多个。因此我的计划是这样：
> 
> 1. 增加一个`build.entries`配置，默认为`entries`，可以设定为`pages`
> 2. 对于所有的入口，统一逻辑：
>    
>    1. 目录下的`*.js`和`*/index.js`（ts、tsx、jsx同理）都认为是一个入口
>    2. 目录下的`*.config.js`和`*/config.js`都认为是配置
>    3. 目录下的`*.ejs`和`*/index.ejs`都认为是HTML模板
> 
> 按照上面的逻辑，可以保持默认情况和现在完全一样，但支持常见的`pages`寻找入口。`pages/*`会变成`*-stable.html`、`*-insiders.html`这样的产出
> 
> @superw-123 看下这样是否可行，你对output有没有特殊的要求

all right！对ouput无特殊要求，目前的编译产出符合需求
