### ISSUE TITLE
低版本手机搭载的浏览器页面无法加载

### ISSUE THREAD

**Issue by Moirafu** [ecomfe/reskript#51]
浏览器信息：
<img width="395" alt="屏幕快照 2021-04-29 下午10 28 14" src="https://user-images.githubusercontent.com/24188762/116567459-39ed9180-a93a-11eb-853d-6796b1278719.png">

测试发现不使用classnames时页面可正常加载，使用classnames页面报错
<img width="434" alt="835f9e904e954cf151c764c3b" src="https://user-images.githubusercontent.com/24188762/116567790-8769fe80-a93a-11eb-918a-ee6022e26820.png">

**Comment by otakustay** [comment]
辛苦你帮我测试一个东西。

1. 找到`node_modules/ecomfe/class-names-loader/dist/index.js`
2. 找到里面有一段`return`模板字符串，是一大段代码
3. 把代码中的`const`都替换成`var`，应该有2处，分别是`const hasOwn`和`const css`
4. 删了缓存`node_modules/.cache`重新构建跑一下看是否能解决问题

**Comment by otakustay** [comment]
已通过[@ecomfe/class-names-loader 2.0.0](https://github.com/ecomfe/class-names-loader/blob/master/CHANGELOG.md#200-2021-04-30)修复
