### ISSUE TITLE
支持service worker的构建

### ISSUE THREAD

**Issue by daxuewen** [ecomfe/reskript#53]
PWA场景里，希望service-worker.js. manifest.json 等文件没有hash，且可以使用skr中的一些变量，比如$build，来描述service-worker的版本。

**Comment by otakustay** [comment]
在`manifest.json`中用`$build.xx`是怎么用的？这个json是怎么经过build的来着

**Comment by otakustay** [comment]
针对`service-worker.js`我认为应该单独处理，看起来用[Workbox Plugin](https://developers.google.com/web/tools/workbox/modules/workbox-webpack-plugin)比较合适？

**Comment by otakustay** [comment]
不过考虑到有多feature的情况，我们确定`service-worker.js`只有一个吗？或许需要像`service-worker-stable.js`这样命名？

**Comment by daxuewen** [comment]
> 在`manifest.json`中用`$build.xx`是怎么用的？这个json是怎么经过build的来着

现在 manifest.json 这个场景还没用到，只是看到里面也有版本相关的信息。以 service-worker.js为例，precacheAndRoute([
    {url: '/index.html', revision: $build.version},
]);

**Comment by daxuewen** [comment]
> 不过考虑到有多feature的情况，我们确定`service-worker.js`只有一个吗？或许需要像`service-worker-stable.js`这样命名？

暂时这块还没有遇到需要区分的场景

**Comment by daxuewen** [comment]
> 针对`service-worker.js`我认为应该单独处理，看起来用[Workbox Plugin](https://developers.google.com/web/tools/workbox/modules/workbox-webpack-plugin)比较合适？

上次是修改 workbox cdn（modulePathPrefix），插件看起来不能配置，我再看看。

**Comment by otakustay** [comment]
我看了一下，如果用`InjectManifestPlugin`的话，会生成这样的代码（`/xba/assets`是自定义的`publicPath`）：

```js
precacheAndRoute([
    {revision: '4b1f47478ea996a66a122e052b65f352', url: '/xba/assets/../index-stable.html'},
    {revision: null, url: '/xba/assets/index.25fb981658f95193eb8d.js'},
]),
```

它会把所有的编译产出都执行`precacheAndRoute`管理起来。

对于你这边的需求，我理解更像是一个顶层的service worker希望把底下子应用的都管起来，此时并没有任何可以注入的manifest可言。对于这种情况，只需要`webpack`做一次构建就行，大致如下：

1. 放在`src/service-worker.js`下navigator.serviceWorker.register`
2. 可以是任意内容，但如果有`self.__WB_MANIFEST`这段标记，会打开`InjectManifestPlugin`，否则就只做构建
3. 产出放在`dist/service-worker-{featureSetName}.js`，如`service-worker-stable.js`
4. 如果有`service-worker.js`，则自动在HTML中注入`navigator.serviceWorker.register`的相关代码，不需要手动修改HTML模板，会根据构建的target去注入不同的service worker脚本

因为`service-worker.js`是由`webpack`构建出来的，所以支持一切skr支持的能力，如`$features`和`$build`

**Comment by otakustay** [comment]
我修改一下标题，更好地说明需要做的事情

**Comment by otakustay** [comment]
@daxuewen 我了解了一下你这边的情况，你这边的`service-worker.js`应该是由一个framework构建出来的，最终发布并不是html，是这样么？

**Comment by otakustay** [comment]
@daxuewen 你的问题我计划用 https://github.com/ecomfe/reskript/issues/56 解决

**Comment by otakustay** [comment]
@daxuewen 参考 https://ecomfe.github.io/reskript/docs/advanced/multiple-entry#%E8%87%AA%E5%AE%9A%E4%B9%89%E5%85%A5%E5%8F%A3%E9%85%8D%E7%BD%AE
