### ISSUE TITLE
skr babel 构建会丢失目录结构

### ISSUE THREAD

**Issue by gxy01** [ecomfe/reskript#61]
比如 src/index.js 会被 src/ttt/index.js覆盖。

另外，
https://ecomfe.github.io/reskript/docs/cli/babel/#%E7%BC%96%E8%AF%91%E6%95%B4%E4%B8%AA%E7%9B%AE%E5%BD%95 这里的命令应该是 skr babel 吧

**Comment by otakustay** [comment]
@gxy01 你使用的Node版本是什么，我在考虑是不是和 #59 能不能合并发布
