### ISSUE TITLE
微前端(如qiankun)使用场景里，子系统静态资源publicPath的问题

### ISSUE THREAD

**Issue by daxuewen** [ecomfe/reskript#62]
微前端(如qiankun)使用场景里，子系统静态资源的路径和当前页面URL没有直接关系，这个时候推荐在skr配置里自己加上，还是考虑skr的publicPath自动获取ip和端口拼接上

**Comment by otakustay** [comment]
这个场景我不是很清楚，能否有个具体示例

**Comment by daxuewen** [comment]
> 这个场景我不是很清楚，能否有个具体示例

主系统是: http://127.0.0.1:8002 对应的静态资源是 http://127.0.0.1:8002/assets/xxxx
子系统是：http://127.0.0.1:8003，单独跑没问题

如果在主系统里加载子系统，这个时候，页面链接为 http://127.0.0.1:8002/{子系统baseUrl} ，这个时候加载子系统的JS也会用 http://127.0.0.1:8002/assets/xxx ，实际取不到

**Comment by otakustay** [comment]
只需要子系统在启动的时候自动把`publicPath`设成完整的路径，而不是用相对路径就能解决这问题对吧

**Comment by daxuewen** [comment]
> 只需要子系统在启动的时候自动把`publicPath`设成完整的路径，而不是用相对路径就能解决这问题对吧

嗯，是的

**Comment by otakustay** [comment]
这里有个问题，一个站点可以通过`localhost`、`127.0.0.1`和局域网IP访问，在构建的时候是不确定运行时用的是哪个的，首先要提供一个参数比如`--host=localhost | loopback | ip`来指定这东西才行，这样OK吗？如果不指定这个参数，默认追加成localhost

**Comment by otakustay** [comment]
另外现在是不是存在静态资源没有CORS头的问题，需要`skr dev`自动给加上？@daxuewen
