### ISSUE TITLE
自定义测试配置 jest.config.js 不生效

### ISSUE THREAD

**Issue by nick-ChenZe** [ecomfe/reskript#63]
我需要指定一个目录去测试, 类似
```
 skr test --coverage --cwd=./src/utils/ --target=react
```
执行后会有如下的error
```
  {
      "moduleNameMapper": {
        "/@\/(.*)$/": "/Volumes/Code/baidu/icafe/front-app/src/utils/src/$1"
      },
      "resolver": undefined
  }
```
`src/utils/src` 嵌套了，所以我想要在根目录写死 <RootDir>

![image](https://user-images.githubusercontent.com/12672355/121128521-1b928400-c85e-11eb-88e6-35e350200b26.png)

结果还是上面的error

**Comment by otakustay** [comment]
你不能用`--cwd`这个参数，它指定了`<rootDir>`肯定会出问题。这个问题转化为`skr test`如何指定一个目录作为测试吧，考虑新增功能

**Comment by otakustay** [comment]
参考 https://ecomfe.github.io/reskript/docs/cli/test#%E5%8F%82%E6%95%B0 指定测试范围
