### ISSUE TITLE
在skr lint返回码分等级

### ISSUE THREAD

**Issue by swqddx** [ecomfe/reskript#71]
现在skr lint代码检查无等级划分，仅有warning也会使得git钩子和有error返回同样的值，使提交失败。
**建议划分规范检测的结果等级，以根据框架用户根据自身需求配置规范要求。**

**Comment by otakustay** [comment]
会在`skr lint`上加一个`--strict`参数。默认行为变更为warning全部放过（但会在最后的提示信息上变化），如果开了`--strict`的话则warning会导致状态码25退出
