### ISSUE TITLE
是移除了默认路由的支持么？

### ISSUE THREAD

**Issue by MBearo** [ecomfe/reskript#82]

**Comment by otakustay** [comment]
默认路由是指什么？reskript完全没管路由这事

**Comment by MBearo** [comment]
是不考虑路由，还是考虑以后添加路由可选项?

**Comment by otakustay** [comment]
你的路由是指react-router的整合还是命令行的子命令调用之类的……

**Comment by MBearo** [comment]
react-router的整合

**Comment by otakustay** [comment]
当前还没有计划侵入到业务的代码中去做事，估计后面会有类似skr stack的全套解决方案来做这些，不过比较遥远吧
