### ISSUE TITLE
文档链接的相对路径有问题，第一次点击会404

### ISSUE THREAD

**Issue by nick-ChenZe** [ecomfe/reskript#83]
复现路径 
1. 通过https://ecomfe.github.io/reskript/docs/faq 链接打开
2. 点击 _复用现在的loader_

如果从其他页面进入
1. 通过 https://ecomfe.github.io/reskript/docs/getting-started 打开
2. 进去faq
3. 点击 _复用现在的loader_ 正常

**Comment by otakustay** [comment]
参考[这里的说法](https://github.com/facebook/docusaurus/issues/5026#issuecomment-865166200)，应该加一个`trailingSlash: false`配置，回头测试一下

**Comment by otakustay** [comment]
参考[这里的说法](https://github.com/facebook/docusaurus/issues/5026#issuecomment-865166200)，应该加一个`trailingSlash: false`配置，回头测试一下
