### ISSUE TITLE
eslint 配置引入config-lint/eslint文件，vs code eslint插件找不到文件导致插件失效

### ISSUE THREAD

**Issue by swqddx** [ecomfe/reskript#86]
经测试，@reskript/config-lint package.json中的exports关于config文件夹下的通配写法不生效（貌似不支持）

**Comment by otakustay** [comment]
也请提供一下你的node版本，我来试一试

**Comment by swqddx** [comment]
node版本为 v14.6.0

**Comment by otakustay** [comment]
参考 #59 ，考虑到ESM和`node:`的支持，我们把版本限制在了`14.13.1`以上。我手头上的M1现在编译不出来`14.6.0`，但在`14.17.3`下试了是没有问题的

不知道你是否方便更新Node的版本，同样是14内的小版本，应该是保持兼容的

**Comment by swqddx** [comment]
哦哦这样子，没问题的
