### ISSUE TITLE
支持 jest import 字符串

### ISSUE THREAD

**Issue by LeuisKen** [ecomfe/reskript#94]
希望可以约定一个固定的后缀，如 `.tpl` 会 import string 进来。

具体的场景是，编写单测的时候，会存在一些模板文件，比如 markdown parser 的测试用例，测试用例的输入是一个很大的 markdown 文本字符串，和 case 写在一起就很难受。有了这个能力，就可以以 `case.md.tpl` 这样的形式存在了。

都用 tpl 做后缀的好处是统一，坏处就是高亮需要手动再配置一下，不过我觉得 tpl 都不会很复杂，没有高亮问题不大。

**Comment by otakustay** [comment]
本来想除了能识别的以外全给搞到raw loader上，但这么搞以后再改就会BREAKING了，也不合适

我想还是尽量列一下后缀吧，`md`、`mdx`、`txt`、`tpl`，先这些，XML类的一堆东西也不好说要啥loader先不放进来
